In [36]:
from pathlib import Path
import polars as pl
import numpy as np

PROJECT_ROOT = Path().resolve().parent  # since you're in notebooks/
DATA_PATH = PROJECT_ROOT / "data" / "WA_Fn-UseC_-Telco-Customer-Churn.csv"

df = pl.read_csv(DATA_PATH)

print(df.shape)
df.head()

(7043, 21)

shape: (5, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cus ┆ gen ┆ Sen ┆ Par ┆ Dep ┆ ten ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Mon ┆ Tot ┆ Chu │
│ tom ┆ der ┆ ior ┆ tne ┆ end ┆ ure ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ thl ┆ alC ┆ rn  │
│ erI ┆ --- ┆ Cit ┆ r   ┆ ent ┆ --- ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct  ┆ ess ┆ tMe ┆ yCh ┆ har ┆ --- │
│ D   ┆ str ┆ ize ┆ --- ┆ s   ┆ i64 ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt  ┆ TV  ┆ Mov ┆ --- ┆ Bil ┆ tho ┆ arg ┆ ges ┆ str │
│ --- ┆     ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ s   ┆ ice ┆ ty  ┆ --- ┆ tio ┆ --- ┆ --- ┆ ies ┆ str ┆ lin ┆ d   ┆ es  ┆ --- ┆     │
│ str ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ n   ┆ str ┆ str ┆ --- ┆     ┆ g   ┆ --- ┆ --- ┆ f64 ┆     │
│     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 759 ┆ Fem ┆ 0   ┆ Yes ┆ No  ┆ 1   ┆ No  ┆ No  ┆ DSL ┆ No  ┆ Yes ┆ No  ┆ No  ┆ No  ┆ No  ┆ Mon ┆ Yes ┆ Ele ┆ 29. ┆ 29. ┆ No  │
│ 0-V ┆ ale ┆     ┆     ┆     ┆     ┆     ┆ pho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th- ┆     ┆ ctr ┆ 85  ┆ 85  ┆     │
│ HVE ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to- ┆     ┆ oni ┆     ┆     ┆     │
│ G   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ser ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mon ┆     ┆ c   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆ che ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     │
│ 557 ┆ Mal ┆ 0   ┆ No  ┆ No  ┆ 34  ┆ Yes ┆ No  ┆ DSL ┆ Yes ┆ No  ┆ Yes ┆ No  ┆ No  ┆ No  ┆ One ┆ No  ┆ Mai ┆ 56. ┆ 188 ┆ No  │
│ 5-G ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yea ┆     ┆ led ┆ 95  ┆ 9.5 ┆     │
│ NVD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆ che ┆     ┆     ┆     │
│ E   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     │
│ 366 ┆ Mal ┆ 0   ┆ No  ┆ No  ┆ 2   ┆ Yes ┆ No  ┆ DSL ┆ Yes ┆ Yes ┆ No  ┆ No  ┆ No  ┆ No  ┆ Mon ┆ Yes ┆ Mai ┆ 53. ┆ 108 ┆ Yes │
│ 8-Q ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th- ┆     ┆ led ┆ 85  ┆ .15 ┆     │
│ PYB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to- ┆     ┆ che ┆     ┆     ┆     │
│ K   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mon ┆     ┆ ck  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     │
│ 779 ┆ Mal ┆ 0   ┆ No  ┆ No  ┆ 45  ┆ No  ┆ No  ┆ DSL ┆ Yes ┆ No  ┆ Yes ┆ Yes ┆ No  ┆ No  ┆ One ┆ No  ┆ Ban ┆ 42. ┆ 184 ┆ No  │
│ 5-C ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ pho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yea ┆     ┆ k   ┆ 3   ┆ 0.7 ┆     │
│ FOC ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆ tra ┆     ┆ 5   ┆     │
│ W   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ser ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nsf ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (au ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c)  ┆     ┆     ┆     │
│ 923 ┆ Fem ┆ 0   ┆ No  ┆ No  ┆ 2   ┆ Yes ┆ No  ┆ Fib ┆ No  ┆ No  ┆ No  ┆ No  ┆ No  ┆ No  ┆ Mon ┆ Yes ┆ Ele ┆ 70. ┆ 151 ┆ Yes │
│ 7-H ┆ ale ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆ th- ┆     ┆ ctr ┆ 7   ┆ .65 ┆     │
│ QIT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ opt ┆     ┆     ┆     ┆     ┆     ┆     ┆ to- ┆     ┆ oni ┆     ┆     ┆     │
│ U   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆ mon ┆     ┆ c   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆ che ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [26]:
df.describe()

shape: (9, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ cus ┆ gen ┆ Sen ┆ Par ┆ Dep ┆ ten ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Mon ┆ Tot ┆ Chu │
│ tis ┆ tom ┆ der ┆ ior ┆ tne ┆ end ┆ ure ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ thl ┆ alC ┆ rn  │
│ tic ┆ erI ┆ --- ┆ Cit ┆ r   ┆ ent ┆ --- ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct  ┆ ess ┆ tMe ┆ yCh ┆ har ┆ --- │
│ --- ┆ D   ┆ str ┆ ize ┆ --- ┆ s   ┆ f64 ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt  ┆ TV  ┆ Mov ┆ --- ┆ Bil ┆ tho ┆ arg ┆ ges ┆ str │
│ str ┆ --- ┆     ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ s   ┆ ice ┆ ty  ┆ --- ┆ tio ┆ --- ┆ --- ┆ ies ┆ str ┆ lin ┆ d   ┆ es  ┆ --- ┆     │
│     ┆ str ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ n   ┆ str ┆ str ┆ --- ┆     ┆ g   ┆ --- ┆ --- ┆ f64 ┆     │
│     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 704 ┆ 703 ┆ 704 │
│ nt  ┆ 3   ┆ 3   ┆ 3.0 ┆ 3   ┆ 3   ┆ 3.0 ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3.0 ┆ 2.0 ┆ 3   │
│ nul ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 11. ┆ 0   │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ nul ┆ nul ┆ 0.1 ┆ nul ┆ nul ┆ 32. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 64. ┆ 228 ┆ nul │
│ n   ┆ l   ┆ l   ┆ 621 ┆ l   ┆ l   ┆ 371 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 761 ┆ 3.3 ┆ l   │
│     ┆     ┆     ┆ 47  ┆     ┆     ┆ 149 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 692 ┆ 004 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 41  ┆     │
│ std ┆ nul ┆ nul ┆ 0.3 ┆ nul ┆ nul ┆ 24. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 30. ┆ 226 ┆ nul │
│     ┆ l   ┆ l   ┆ 686 ┆ l   ┆ l   ┆ 559 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 090 ┆ 6.7 ┆ l   │
│     ┆     ┆     ┆ 12  ┆     ┆     ┆ 481 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 047 ┆ 713 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62  ┆     │
│ min ┆ 000 ┆ Fem ┆ 0.0 ┆ No  ┆ No  ┆ 0.0 ┆ No  ┆ No  ┆ DSL ┆ No  ┆ No  ┆ No  ┆ No  ┆ No  ┆ No  ┆ Mon ┆ No  ┆ Ban ┆ 18. ┆ 18. ┆ No  │
│     ┆ 2-O ┆ ale ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th- ┆     ┆ k   ┆ 25  ┆ 8   ┆     │
│     ┆ RFB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to- ┆     ┆ tra ┆     ┆     ┆     │
│     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mon ┆     ┆ nsf ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (au ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c)  ┆     ┆     ┆     │
│ 25% ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 9.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 35. ┆ 401 ┆ nul │
│     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 5   ┆ .5  ┆ l   │
│ 50% ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 29. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 70. ┆ 139 ┆ nul │
│     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 35  ┆ 7.6 ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     │
│ 75% ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 55. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 89. ┆ 379 ┆ nul │
│     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 85  ┆ 4.5 ┆ l   │
│ max ┆ 999 ┆ Mal ┆ 1.0 ┆ Yes ┆ Yes ┆ 72. ┆ Yes ┆ Yes ┆ No  ┆ Yes ┆ Yes ┆ Yes ┆ Yes ┆ Yes ┆ Yes ┆ Two ┆ Yes ┆ Mai ┆ 118 ┆ 868 ┆ Yes │
│     ┆ 5-H ┆ e   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yea ┆     ┆ led ┆ .75 ┆ 4.8 ┆     │
│     ┆ OTO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆ che ┆     ┆     ┆     │
│     ┆ H   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [27]:
df.schema

Schema([('customerID', String),
        ('gender', String),
        ('SeniorCitizen', Int64),
        ('Partner', String),
        ('Dependents', String),
        ('tenure', Int64),
        ('PhoneService', String),
        ('MultipleLines', String),
        ('InternetService', String),
        ('OnlineSecurity', String),
        ('OnlineBackup', String),
        ('DeviceProtection', String),
        ('TechSupport', String),
        ('StreamingTV', String),
        ('StreamingMovies', String),
        ('Contract', String),
        ('PaperlessBilling', String),
        ('PaymentMethod', String),
        ('MonthlyCharges', Float64),
        ('TotalCharges', Float64),
        ('Churn', String)])

In [38]:
missing_df = df.select(
    pl.all().null_count().name.suffix("_nulls")
)
missing_df

shape: (1, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cus ┆ gen ┆ Sen ┆ Par ┆ Dep ┆ ten ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Mon ┆ Tot ┆ Chu │
│ tom ┆ der ┆ ior ┆ tne ┆ end ┆ ure ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ thl ┆ alC ┆ rn_ │
│ erI ┆ _nu ┆ Cit ┆ r_n ┆ ent ┆ _nu ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct_ ┆ ess ┆ tMe ┆ yCh ┆ har ┆ nul │
│ D_n ┆ lls ┆ ize ┆ ull ┆ s_n ┆ lls ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt_ ┆ TV_ ┆ Mov ┆ nul ┆ Bil ┆ tho ┆ arg ┆ ges ┆ ls  │
│ ull ┆ --- ┆ n_n ┆ s   ┆ ull ┆ --- ┆ _nu ┆ s_n ┆ ice ┆ ty_ ┆ _nu ┆ tio ┆ nul ┆ nul ┆ ies ┆ ls  ┆ lin ┆ d_n ┆ es_ ┆ _nu ┆ --- │
│ s   ┆ u32 ┆ ull ┆ --- ┆ s   ┆ u32 ┆ lls ┆ ull ┆ _nu ┆ nul ┆ lls ┆ n_n ┆ ls  ┆ ls  ┆ _nu ┆ --- ┆ g_n ┆ ull ┆ nul ┆ lls ┆ u32 │
│ --- ┆     ┆ s   ┆ u32 ┆ --- ┆     ┆ --- ┆ s   ┆ lls ┆ ls  ┆ --- ┆ ull ┆ --- ┆ --- ┆ lls ┆ u32 ┆ ull ┆ s   ┆ ls  ┆ --- ┆     │
│ u32 ┆     ┆ --- ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ --- ┆ --- ┆ u32 ┆ s   ┆ u32 ┆ u32 ┆ --- ┆     ┆ s   ┆ --- ┆ --- ┆ u32 ┆     │
│     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆     ┆ --- ┆ u32 ┆ u32 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 11  ┆ 0   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [39]:
missing_pct = df.select([
    (pl.all().null_count() / df.height).name.suffix("_pct")
])
missing_pct

shape: (1, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cus ┆ gen ┆ Sen ┆ Par ┆ Dep ┆ ten ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Mon ┆ Tot ┆ Chu │
│ tom ┆ der ┆ ior ┆ tne ┆ end ┆ ure ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ thl ┆ alC ┆ rn_ │
│ erI ┆ _pc ┆ Cit ┆ r_p ┆ ent ┆ _pc ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct_ ┆ ess ┆ tMe ┆ yCh ┆ har ┆ pct │
│ D_p ┆ t   ┆ ize ┆ ct  ┆ s_p ┆ t   ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt_ ┆ TV_ ┆ Mov ┆ pct ┆ Bil ┆ tho ┆ arg ┆ ges ┆ --- │
│ ct  ┆ --- ┆ n_p ┆ --- ┆ ct  ┆ --- ┆ _pc ┆ s_p ┆ ice ┆ ty_ ┆ _pc ┆ tio ┆ pct ┆ pct ┆ ies ┆ --- ┆ lin ┆ d_p ┆ es_ ┆ _pc ┆ f64 │
│ --- ┆ f64 ┆ ct  ┆ f64 ┆ --- ┆ f64 ┆ t   ┆ ct  ┆ _pc ┆ pct ┆ t   ┆ n_p ┆ --- ┆ --- ┆ _pc ┆ f64 ┆ g_p ┆ ct  ┆ pct ┆ t   ┆     │
│ f64 ┆     ┆ --- ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆ t   ┆ --- ┆ --- ┆ ct  ┆ f64 ┆ f64 ┆ t   ┆     ┆ ct  ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆ --- ┆     ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ f64 ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 015 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62  ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [40]:
target_dist = df.group_by("Churn").len()
target_dist

shape: (2, 2)
┌───────┬──────┐
│ Churn ┆ len  │
│ ---   ┆ ---  │
│ str   ┆ u32  │
╞═══════╪══════╡
│ No    ┆ 5174 │
│ Yes   ┆ 1869 │
└───────┴──────┘

In [41]:
target_dist = target_dist.with_columns(
    (pl.col("len") / pl.col("len").sum()).alias("ratio")
)
target_dist

shape: (2, 3)
┌───────┬──────┬─────────┐
│ Churn ┆ len  ┆ ratio   │
│ ---   ┆ ---  ┆ ---     │
│ str   ┆ u32  ┆ f64     │
╞═══════╪══════╪═════════╡
│ No    ┆ 5174 ┆ 0.73463 │
│ Yes   ┆ 1869 ┆ 0.26537 │
└───────┴──────┴─────────┘

In [32]:
categorical_cols = [
    col for col, dtype in df.schema.items()
    if dtype == pl.Utf8
]

numerical_cols = [
    col for col, dtype in df.schema.items()
    if dtype in (pl.Int64, pl.Float64)
]
print(categorical_cols)
print(numerical_cols)

['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [42]:
cardinality = df.select([
    pl.col(col).n_unique().alias(col)
    for col in categorical_cols
])
cardinality

shape: (1, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cus ┆ gen ┆ Par ┆ Dep ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Chu │
│ tom ┆ der ┆ tne ┆ end ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ rn  │
│ erI ┆ --- ┆ r   ┆ ent ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct  ┆ ess ┆ tMe ┆ --- │
│ D   ┆ u32 ┆ --- ┆ s   ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt  ┆ TV  ┆ Mov ┆ --- ┆ Bil ┆ tho ┆ u32 │
│ --- ┆     ┆ u32 ┆ --- ┆ --- ┆ s   ┆ ice ┆ ty  ┆ --- ┆ tio ┆ --- ┆ --- ┆ ies ┆ u32 ┆ lin ┆ d   ┆     │
│ u32 ┆     ┆     ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ --- ┆ u32 ┆ n   ┆ u32 ┆ u32 ┆ --- ┆     ┆ g   ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆     ┆ --- ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 704 ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 2   ┆ 4   ┆ 2   │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [34]:
print(df.select(numerical_cols).describe())

shape: (9, 5)
┌────────────┬───────────────┬───────────┬────────────────┬──────────────┐
│ statistic  ┆ SeniorCitizen ┆ tenure    ┆ MonthlyCharges ┆ TotalCharges │
│ ---        ┆ ---           ┆ ---       ┆ ---            ┆ ---          │
│ str        ┆ f64           ┆ f64       ┆ f64            ┆ f64          │
╞════════════╪═══════════════╪═══════════╪════════════════╪══════════════╡
│ count      ┆ 7043.0        ┆ 7043.0    ┆ 7043.0         ┆ 7032.0       │
│ null_count ┆ 0.0           ┆ 0.0       ┆ 0.0            ┆ 11.0         │
│ mean       ┆ 0.162147      ┆ 32.371149 ┆ 64.761692      ┆ 2283.300441  │
│ std        ┆ 0.368612      ┆ 24.559481 ┆ 30.090047      ┆ 2266.771362  │
│ min        ┆ 0.0           ┆ 0.0       ┆ 18.25          ┆ 18.8         │
│ 25%        ┆ 0.0           ┆ 9.0       ┆ 35.5           ┆ 401.5        │
│ 50%        ┆ 0.0           ┆ 29.0      ┆ 70.35          ┆ 1397.65      │
│ 75%        ┆ 0.0           ┆ 55.0      ┆ 89.85          ┆ 3794.5       │
│ max        ┆ 1.0           ┆ 72.0      ┆ 118.75         ┆ 8684.8       │
└────────────┴───────────────┴───────────┴────────────────┴──────────────┘

In [44]:
corr = df.select(numerical_cols).corr()
print(corr)

shape: (4, 4)
┌───────────────┬──────────┬────────────────┬──────────────┐
│ SeniorCitizen ┆ tenure   ┆ MonthlyCharges ┆ TotalCharges │
│ ---           ┆ ---      ┆ ---            ┆ ---          │
│ f64           ┆ f64      ┆ f64            ┆ f64          │
╞═══════════════╪══════════╪════════════════╪══════════════╡
│ 1.0           ┆ 0.016567 ┆ 0.220173       ┆ NaN          │
│ 0.016567      ┆ 1.0      ┆ 0.2479         ┆ NaN          │
│ 0.220173      ┆ 0.2479   ┆ 1.0            ┆ NaN          │
│ NaN           ┆ NaN      ┆ NaN            ┆ NaN          │
└───────────────┴──────────┴────────────────┴──────────────┘

In [45]:
contract_churn = df.group_by(["Contract", "Churn"]).len()
contract_churn

shape: (6, 3)
┌────────────────┬───────┬──────┐
│ Contract       ┆ Churn ┆ len  │
│ ---            ┆ ---   ┆ ---  │
│ str            ┆ str   ┆ u32  │
╞════════════════╪═══════╪══════╡
│ Month-to-month ┆ No    ┆ 2220 │
│ Month-to-month ┆ Yes   ┆ 1655 │
│ Two year       ┆ No    ┆ 1647 │
│ One year       ┆ Yes   ┆ 166  │
│ One year       ┆ No    ┆ 1307 │
│ Two year       ┆ Yes   ┆ 48   │
└────────────────┴───────┴──────┘

In [46]:
contract_churn = contract_churn.with_columns(
    (pl.col("len") / pl.col("len").sum().over("Contract")).alias("ratio")
)
contract_churn

shape: (6, 4)
┌────────────────┬───────┬──────┬──────────┐
│ Contract       ┆ Churn ┆ len  ┆ ratio    │
│ ---            ┆ ---   ┆ ---  ┆ ---      │
│ str            ┆ str   ┆ u32  ┆ f64      │
╞════════════════╪═══════╪══════╪══════════╡
│ Month-to-month ┆ No    ┆ 2220 ┆ 0.572903 │
│ Month-to-month ┆ Yes   ┆ 1655 ┆ 0.427097 │
│ Two year       ┆ No    ┆ 1647 ┆ 0.971681 │
│ One year       ┆ Yes   ┆ 166  ┆ 0.112695 │
│ One year       ┆ No    ┆ 1307 ┆ 0.887305 │
│ Two year       ┆ Yes   ┆ 48   ┆ 0.028319 │
└────────────────┴───────┴──────┴──────────┘

In [47]:
df.select([
    pl.col(col).n_unique().alias(col)
    for col in df.columns
]).sort(by=df.columns[0])

shape: (1, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cus ┆ gen ┆ Sen ┆ Par ┆ Dep ┆ ten ┆ Pho ┆ Mul ┆ Int ┆ Onl ┆ Onl ┆ Dev ┆ Tec ┆ Str ┆ Str ┆ Con ┆ Pap ┆ Pay ┆ Mon ┆ Tot ┆ Chu │
│ tom ┆ der ┆ ior ┆ tne ┆ end ┆ ure ┆ neS ┆ tip ┆ ern ┆ ine ┆ ine ┆ ice ┆ hSu ┆ eam ┆ eam ┆ tra ┆ erl ┆ men ┆ thl ┆ alC ┆ rn  │
│ erI ┆ --- ┆ Cit ┆ r   ┆ ent ┆ --- ┆ erv ┆ leL ┆ etS ┆ Sec ┆ Bac ┆ Pro ┆ ppo ┆ ing ┆ ing ┆ ct  ┆ ess ┆ tMe ┆ yCh ┆ har ┆ --- │
│ D   ┆ u32 ┆ ize ┆ --- ┆ s   ┆ u32 ┆ ice ┆ ine ┆ erv ┆ uri ┆ kup ┆ tec ┆ rt  ┆ TV  ┆ Mov ┆ --- ┆ Bil ┆ tho ┆ arg ┆ ges ┆ u32 │
│ --- ┆     ┆ n   ┆ u32 ┆ --- ┆     ┆ --- ┆ s   ┆ ice ┆ ty  ┆ --- ┆ tio ┆ --- ┆ --- ┆ ies ┆ u32 ┆ lin ┆ d   ┆ es  ┆ --- ┆     │
│ u32 ┆     ┆ --- ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ --- ┆ --- ┆ u32 ┆ n   ┆ u32 ┆ u32 ┆ --- ┆     ┆ g   ┆ --- ┆ --- ┆ u32 ┆     │
│     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆     ┆     ┆ u32 ┆     ┆ --- ┆ u32 ┆ u32 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 704 ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 73  ┆ 2   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 3   ┆ 2   ┆ 4   ┆ 158 ┆ 653 ┆ 2   │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 1   ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [48]:
df.select([
    pl.col(col).quantile(0.01).alias(f"{col}_p1")
    for col in numerical_cols
] + [
    pl.col(col).quantile(0.99).alias(f"{col}_p99")
    for col in numerical_cols
])

shape: (1, 8)
┌────────────┬───────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ SeniorCiti ┆ tenure_p1 ┆ MonthlyCha ┆ TotalCharg ┆ SeniorCit ┆ tenure_p9 ┆ MonthlyCh ┆ TotalChar │
│ zen_p1     ┆ ---       ┆ rges_p1    ┆ es_p1      ┆ izen_p99  ┆ 9         ┆ arges_p99 ┆ ges_p99   │
│ ---        ┆ f64       ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆           ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0        ┆ 1.0       ┆ 19.2       ┆ 19.9       ┆ 1.0       ┆ 72.0      ┆ 114.75    ┆ 8041.65   │
└────────────┴───────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘